# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmsapp', '0006_auto_20160223_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=80, null=True, verbose_name=b'Link title')),
                ('link_url', models.CharField(max_length=300, null=True, verbose_name=b'Link URL')),
                ('buildingKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmsapp.Building')),
            ],
        ),
    ]
