# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmsapp', '0007_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='buildingKey',
            new_name='Building_Key',
        ),
    ]
