# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmsapp', '0009_auto_20160224_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['link_name']},
        ),
        migrations.RemoveField(
            model_name='link',
            name='Building_Key',
        ),
        migrations.AddField(
            model_name='building',
            name='links',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bmsapp.Link'),
        ),
        migrations.AlterField(
            model_name='link',
            name='link_name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name=b'Link title'),
        ),
        migrations.AlterField(
            model_name='link',
            name='link_url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name=b'Link URL'),
        ),
    ]
